//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discus
    {
        public Discus()
        {
            this.Answer = new HashSet<Answer>();
        }
    
        public int ID { get; set; }
        public int TopicsID { get; set; }
        public System.DateTime Date { get; set; }
        public string Author { get; set; }
        public string Text { get; set; }
    
        public virtual Topics Topics { get; set; }
        public virtual ICollection<Answer> Answer { get; set; }
    }
}
