//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topics
    {
        public Topics()
        {
            this.Discus = new HashSet<Discus>();
        }
    
        public int ID { get; set; }
        public string TopicName { get; set; }
        public System.DateTime Date { get; set; }
        public string Author { get; set; }
    
        public virtual ICollection<Discus> Discus { get; set; }
    }
}
